---
title: "Lab 10"
author: "CB"
date: "`r Sys.Date()`"
output: github_document
always_allow_html: true
---
```
{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(RSQLite)
library(DBI)
```
```{r}
# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)
```
```{r}
dbListTables(con)
```

```{sql, connection=con}
PRAGMA table_info(actor)
```

```{r}
#in order to do the SQL query FROM R use the dbGetQuery command to do it
dbGetQuery(con, "PRAGMA table_info(actor)")
```
## Exercise 1

```{r}
dbGetQuery(con, "
SELECT actor_id, first_name, last_name
FROM actor
ORDER by last_name, first_name")
```
```{sql, connection=con}
SELECT actor_id, first_name, last_name
FROM actor
ORDER by last_name, first_name
```
```{r}
# clean up
dbDisconnect(con)
```

